### ISSUE TITLE
Could not find your board, make sure it's plugged into USB, aka cannot run devcon.exe

### ISSUE THREAD

**Issue by i-make-robots** [davidvondle/Upload-And-Retrieve-Source#2]
I'm running Windows 7 as the sole user.
Even though I have 64 bit architecture ia64 version reports an error and quits, so I installed the i386 version of devcon.exe in the arduino-1.0\tools\ folder.
I right clicked on the file in explorer and checked the box in Properties->Compatibility->Run as Administrator
I still get a dimmed screen and a security warning every time I run devcon.exe from the command line.
When I try to upload code from the arduino I get "Could not find your board, make sure it's plugged into USB."

**Comment by davidvondle** [comment]
You will need to run Arduino as an administrator for it to be able to run devcon.  I added this error message to the arduino terminal window and will add it to the readme as well.  Thanks.
